name: Container Security Scan

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 3 * * 2-6  ' # Daily Tuesday-Saturday at 3:00 AM UTC
env:
  REGISTRY: ghcr.io

jobs:
  install-dependencies:
    uses: ./.github/workflows/install-dependencies.yml

  scan:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run environment diagnostics
        run: |
          chmod +x scripts/diagnose-environment.sh
          echo "🔍 Running environment diagnostics..."
          ./scripts/diagnose-environment.sh

      # --- NEW: Discovery Step ---
      - name: Discover container images (generate discovered.yaml)
        run: |
          chmod +x scripts/dimpact-image-discovery.sh
          echo "🔍 Discovering images for scan..."
          ./scripts/dimpact-image-discovery.sh --output-file --check-image-availability
          if [ ! -f discovered.yaml ]; then
            echo "❌ discovered.yaml not found! Discovery failed."
            exit 1
          fi
          echo "✅ discovered.yaml generated."

      # --- SCAN Step ---
      - name: Run container image security scan
        run: |
          chmod +x scripts/dimpact-image-scanner.sh
          echo "🚀 Starting container image security scan..."
          # Use date-prefixed output dir
          SCAN_DATE=$(date +%y%m%d)
          OUTPUT_DIR="./${SCAN_DATE}-dimpact-scan-results"
          # Use max performance for CI
          ./scripts/dimpact-image-scanner.sh \
            --use-discovered \
            --output-dir "$OUTPUT_DIR" \
            --performance max
          echo "✅ Scan complete. Results in $OUTPUT_DIR"

      # --- REPORT Step ---
      - name: Generate consolidated security report
        run: |
          chmod +x scripts/dimpact-image-report.sh
          SCAN_DATE=$(date +%y%m%d)
          OUTPUT_DIR="./${SCAN_DATE}-dimpact-scan-results"
          if [ ! -d "$OUTPUT_DIR" ]; then
            echo "❌ Scan output dir $OUTPUT_DIR not found!"
            exit 1
          fi
          ./scripts/dimpact-image-report.sh --input-dir "$OUTPUT_DIR"

      - name: Post-process scan results
        run: |
          chmod +x scripts/dimpact-scan-postprocess.sh
          SCAN_DATE=$(date -u +"%Y-%m-%d")
          SCAN_TIMESTAMP=$(date -u +"%Y%m%d_%H%M%S")
          ./scripts/dimpact-scan-postprocess.sh \
            "$SCAN_DATE" \
            "$SCAN_TIMESTAMP" \
            "${{ github.run_id }}" \
            "${{ github.run_number }}" \
            "${{ github.sha }}" \
            "${{ github.ref }}" \
            "${{ github.actor }}" \
            "${{ github.event_name }}"
